name: ai_project
description: "Grade 12 Academic Guidance Flutter Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Supabase Flutter Package
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset ဖိုင်များ (Logo၊ Offline စာအုပ်များနှင့် မေးခွန်းဟောင်း PDF လမ်းကြောင်းများ)
  assets:
    - assets/
    - assets/books/
    - assets/questions/