name: ai_project
description: "Grade 12 Academic Guidance Flutter Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^25.4.0
  google_generative_ai: ^0.4.7
  http: ^1.2.1
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  syncfusion_flutter_pdfviewer: ^33.2.13
  flutter_dotenv: ^6.0.1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets ဖိုင်များ
  assets:
    - .env
    - assets/
    - assets/texts/
    # PDF ဖတ်စာအုပ်များ
    - assets/books/myanmar.pdf
    - assets/books/english.pdf
    - assets/books/mathematic.pdf
    - assets/books/chemistry.pdf
    - assets/books/physics.pdf
    - assets/books/biology.pdf
    - assets/books/economic.pdf
    # RAG အတွက် အသုံးပြုမည့် Text Data ဖိုင်
    - "assets/texts/project g12 guidance.txt"
    # - assets/questions/